export const GET_DISLIKES_SUCCESS = "GET_DISLIKES_SUCCESS";
export const GET_DISLIKES_ERROR = "GET_DISLIKES_ERROR";
export const DISLIKE_CREATE_SUCCESS = "DISLIKE_CREATE_SUCCESS";
export const DISLIKE_CREATE_ERROR = "DISLIKE_CREATE_ERROR";
export const DISLIKE_DELETE_SUCCESS = "DISLIKE_DELETE_SUCCESS";
export const DISLIKE_DELETE_ERROR = "DISLIKE_DELETE_ERROR";
